### ISSUE TITLE
No separate callbacks available for Sent, Save Draft or Delete operations

### ISSUE THREAD

**Issue by Mike4o** [Telerik-Verified-Plugins/EmailComposer#1]
There is a single call back method available for all the three events (Delete Draft,Save Draft and Send mail), and there is no return code to differentiate these events. However, need is to show different notifications to user based on the completion of each event, i.e. Sent, Save or delete.

Can you please advise how this can be achieved using this plug-in?

Add to the note, there is a phonegap plugin available, which provides this functionality-
https://github.com/GalCohen/EmailComposer-phonegap-plugin/blob/master

window.plugins.emailComposer.showEmailComposerWithCallback(callback,subject,body,toRecipients,ccRecipients,bccRecipients,isHtml,attachments) method has following return code available

0: email composition cancelled (cancel button pressed and draft not saved)
1: email saved (cancel button pressed but draft saved)
2: email sent
3: send failed
4: email not sent (something wrong happened)

Thanks In Advance

**Comment by EddyVerbruggen** [comment]
Hi @Mike4o I'd be interested to learn how that fork extracts the correct value for the callback... but I can't access it (it's probably a private repo). Fastest way is probably if you can zip the repo and email it to me.

Thanks,
Eddy

**Comment by shankarkamra** [comment]
Hi Eddy,

The URL above provided wasn't correct so here is the correct one :
https://github.com/GalCohen/EmailComposer-phonegap-plugin/ 
Appreciate your quick response.

Thanks in Advance

**Comment by EddyVerbruggen** [comment]
That's a really old plugin, you'd better use this one. If you must use that one, please file an issue at their issue tracker, not ours.

**Comment by shankarkamra** [comment]
Hi Eddy ,
I think there is some confusion over here ,we are using telerik verified plugin :
http://plugins.telerik.com/cordova/plugin/emailcomposer
which doesn't have seperate callback functions for these events (Delete Draft,Save Draft and Sendmail) ,so we have raised a support ticket with telerik .

Also we have found that there is phonegap plugin which have separate callbacks fo these events (Delete Draft,Save Draft and Send mail).
https://github.com/GalCohen/EmailComposer-phonegap-plugin/ 

So what we want from you guys is provide the same functionality of separate callbacks in your telerik verified plugin (http://plugins.telerik.com/cordova/plugin/emailcomposer).
So kindly reopen this issue ,appreciate your quick response.
Thanks in Advance

**Comment by EddyVerbruggen** [comment]
Ah, sorry, I misread you. Reopening and I hope to get to this real soon.

**Comment by EddyVerbruggen** [comment]
Hi again, I've now added those callback values you mentioned for iOS. As you can see from the source of the plugin you mentioned this is not possible in Android (noticed this myself when implementing a similar feature in my SocialSharing plugin). So, iOS only, see the readme for details.
